//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarHire
{
    using System;
    using System.Collections.Generic;

    public partial class Booking
    {
        //properties
        public int ID { get; set; }
        public int CarID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }

        public virtual Car Car { get; set; }

        // GetBookingDetail method
        public string GetBookingDetail()
        {
            return string.Format("Car ID : {0}\nMake : {1}\nModel : {2}\nRental Date : {3}\nReturn Date : {4}", Car.ID, Car.Make, Car.Model, StartDate.ToShortDateString(), EndDate.ToShortDateString()); ;
        }
    }
}
