//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarHire
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public Car()
        {
            this.Bookings = new HashSet<Booking>();
        }
        //properties
        public int ID { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Size { get; set; }

        public virtual ICollection<Booking> Bookings { get; set; }

        // ToString Method for displaying details in list box
        public override string ToString()
        {
            return string.Format("{0} - {1}", Make, Model);
        }

        //GetDetail method for full details
        public string GetCarDetail()
        {
            return string.Format("Car ID : {0}\nMake  : {1}\nModel : {2}\n", ID, Make, Model); 
        }
    }
}
